In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf

In [2]:
df = pd.read_csv("Churn_Modelling.csv")

In [3]:
df.head(2)

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   

   Tenure   Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2      0.00              1          1               1   
1       1  83807.86              1          0               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0

In [4]:
tf.__version__

'2.2.0'

In [5]:
df.size

140000

In [26]:
y = df.iloc[:,-1].values

In [27]:
x = df.iloc[:,3:-1].values

In [28]:
print(x)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [29]:
print(y)

[1 0 1 ... 1 1 0]


In [30]:
y

array([1, 0, 1, ..., 1, 1, 0])

In [32]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [33]:
x[:,2] = le.fit_transform(x[:,2])

In [34]:
print(x)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [35]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [36]:
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])], remainder ="passthrough")
x = np.array(ct.fit_transform(x))


In [37]:
print(x)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [38]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.33, random_state=101)

In [39]:
x.shape

(10000, 12)

In [40]:
y.shape

(10000,)

In [42]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

In [43]:
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [44]:
ann = tf.keras.models.Sequential()
ann.add(tf.keras.layers.Dense(units=8,activation='relu'))

In [45]:
ann.add(tf.keras.layers.Dense(units=8, activation="relu"))

In [46]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [47]:
ann.compile(optimizer='adam',loss = 'binary_crossentropy',metrics=['accuracy'])

In [48]:
# For categorical output layer, activation: softmax
# For categorical outputs, loss function ---> categorical_crossentropy


In [49]:
ann.fit(x_train, y_train, batch_size = 32, epochs = 250)

Epoch 1/250
210/210 [==============================] - 0s 2ms/step - loss: 0.5302 - accuracy: 0.7548
Epoch 2/250
210/210 [==============================] - 1s 3ms/step - loss: 0.4603 - accuracy: 0.8004
Epoch 3/250
210/210 [==============================] - 1s 2ms/step - loss: 0.4453 - accuracy: 0.8043
Epoch 4/250
210/210 [==============================] - 0s 2ms/step - loss: 0.4368 - accuracy: 0.8081
Epoch 5/250
210/210 [==============================] - 0s 2ms/step - loss: 0.4310 - accuracy: 0.8110
Epoch 6/250
210/210 [==============================] - 1s 3ms/step - loss: 0.4262 - accuracy: 0.8158
Epoch 7/250
210/210 [==============================] - 1s 3ms/step - loss: 0.4209 - accuracy: 0.8194
Epoch 8/250
210/210 [==============================] - 1s 4ms/step - loss: 0.4137 - accuracy: 0.8236
Epoch 9/250
210/210 [==============================] - 1s 4ms/step - loss: 0.4014 - accuracy: 0.8301
Epoch 10/250
210/210 [==============================] - 1s 3ms/step - loss: 0.3891 - accura

210/210 [==============================] - 0s 2ms/step - loss: 0.3325 - accuracy: 0.8627
Epoch 81/250
210/210 [==============================] - 1s 3ms/step - loss: 0.3322 - accuracy: 0.8634
Epoch 82/250
210/210 [==============================] - 0s 2ms/step - loss: 0.3321 - accuracy: 0.8636
Epoch 83/250
210/210 [==============================] - 1s 2ms/step - loss: 0.3326 - accuracy: 0.8627
Epoch 84/250
210/210 [==============================] - 1s 3ms/step - loss: 0.3319 - accuracy: 0.8634
Epoch 85/250
210/210 [==============================] - 1s 3ms/step - loss: 0.3318 - accuracy: 0.8628
Epoch 86/250
210/210 [==============================] - 0s 2ms/step - loss: 0.3318 - accuracy: 0.8634
Epoch 87/250
210/210 [==============================] - 0s 2ms/step - loss: 0.3317 - accuracy: 0.8618
Epoch 88/250
210/210 [==============================] - 0s 2ms/step - loss: 0.3317 - accuracy: 0.8634
Epoch 89/250
210/210 [==============================] - 1s 4ms/step - loss: 0.3315 - accuracy: 

210/210 [==============================] - 0s 2ms/step - loss: 0.3287 - accuracy: 0.8651
Epoch 159/250
210/210 [==============================] - 0s 1ms/step - loss: 0.3293 - accuracy: 0.8634
Epoch 160/250
210/210 [==============================] - 0s 1ms/step - loss: 0.3297 - accuracy: 0.8643
Epoch 161/250
210/210 [==============================] - 0s 1ms/step - loss: 0.3294 - accuracy: 0.8642
Epoch 162/250
210/210 [==============================] - 0s 2ms/step - loss: 0.3292 - accuracy: 0.8646
Epoch 163/250
210/210 [==============================] - 0s 2ms/step - loss: 0.3291 - accuracy: 0.8649
Epoch 164/250
210/210 [==============================] - 0s 1ms/step - loss: 0.3294 - accuracy: 0.8648
Epoch 165/250
210/210 [==============================] - 0s 1ms/step - loss: 0.3292 - accuracy: 0.8640
Epoch 166/250
210/210 [==============================] - 0s 1ms/step - loss: 0.3291 - accuracy: 0.8654: 0s - loss: 0.3296 - accuracy: 0.86
Epoch 167/250
210/210 [============================

210/210 [==============================] - 0s 2ms/step - loss: 0.3272 - accuracy: 0.8649
Epoch 238/250
210/210 [==============================] - 0s 2ms/step - loss: 0.3277 - accuracy: 0.8648
Epoch 239/250
210/210 [==============================] - 0s 1ms/step - loss: 0.3273 - accuracy: 0.8652
Epoch 240/250
210/210 [==============================] - 0s 1ms/step - loss: 0.3276 - accuracy: 0.8649
Epoch 241/250
210/210 [==============================] - 0s 1ms/step - loss: 0.3276 - accuracy: 0.8663
Epoch 242/250
210/210 [==============================] - 0s 2ms/step - loss: 0.3273 - accuracy: 0.8664
Epoch 243/250
210/210 [==============================] - 0s 2ms/step - loss: 0.3273 - accuracy: 0.8654
Epoch 244/250
210/210 [==============================] - 0s 2ms/step - loss: 0.3273 - accuracy: 0.8649
Epoch 245/250
210/210 [==============================] - 0s 2ms/step - loss: 0.3272 - accuracy: 0.8667
Epoch 246/250
210/210 [==============================] - 0s 1ms/step - loss: 0.3271 - a

In [51]:
print(ann.predict(sc.transform([[1,0,0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]]))>0.5)

[[False]]


In [52]:
y_pred = ann.predict(x_test)

In [53]:
y_pred = (y_pred>0.5)

In [54]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[2492  128]
 [ 340  340]]


In [55]:
accuracy_score(y_test,y_pred)

0.8581818181818182